---
- name: Ensure server's default ip and hostname are in /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv4.address }}" line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}" state=present

- name: Use domain controllers as DNS servers
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
            owner=root group=root mode=0644

- name: Use domain controller as NTP servers
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
             owner=root group=root mode=0644